name: nokos_telegram_generator_test_dc_android
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/nokos_telegram_generator_test_dc
repository: https://github.com/azkadev/nokos_telegram_generator_test_dc
issue_tracker: https://github.com/azkadev/nokos_telegram_generator_test_dc/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - nokos_telegram_generator_test_dc
#   - nokos_telegram_generator_test_dc_flutter
#   - nokos_telegram_generator_test_dc_dart

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 